In [1]:
import sys

sys.path.insert(1, '/Users/od721/Desktop/congestion_pricing/src')

import random_instance
from solution_metrics import optimize_with_solution_metrics as get_metrics

import matplotlib.pyplot as plt

import pandas as pd
import numpy as np
import math
import time

In [2]:
seed = 10
n_node = 50
n_arc_ls = [int(math.ceil(n_node*(n_node-1)*(d/100))) for d in range(1,101,20)]
densities = [a/(n_node*(n_node-1))for a in n_arc_ls]

In [3]:
densities

[0.01020408163265306,
 0.21020408163265306,
 0.41020408163265304,
 0.610204081632653,
 0.810204081632653]

In [4]:
com_ls, density_ls, rate_ls, constraint_util_ls = [], [], [], []
for c in range(1, 5):
    for i, n_arc in enumerate(n_arc_ls):
        print('c-' + str(c)+'_a-'+str(n_arc))
        com_ls.append(c)
        density_ls.append(densities[i])
        ins_ = random_instance.Instance(n_node, n_arc, c, seed)
        _, _, _, arc_util, num_eq, num_ineq, num_binding  = get_metrics(ins_, 3600, log_output=False)
        rate_ls.append(arc_util)
        constraint_util_ls.append(round((num_binding/num_ineq)*100,2))

c-1_a-25
Set parameter Username
Academic license - for non-commercial use only - expires 2022-07-12
c-1_a-515
c-1_a-1005
c-1_a-1495
c-1_a-1985
c-2_a-25
c-2_a-515
c-2_a-1005
c-2_a-1495
c-2_a-1985
c-3_a-25
c-3_a-515
c-3_a-1005
c-3_a-1495
c-3_a-1985
c-4_a-25
c-4_a-515
c-4_a-1005
c-4_a-1495
c-4_a-1985

In [5]:
df = pd.DataFrame()
df['ncom'] = com_ls
df['density'] = density_ls
df['ColumnUtil'] = rate_ls
df['RowUtil'] = constraint_util_ls

In [6]:
df

    ncom   density  ColumnUtil  RowUtil
0      1  0.010204        4.00    64.00
1      1  0.210204       38.83    43.98
2      1  0.410204       34.83    42.34
3      1  0.610204       27.49    43.23
4      1  0.810204       20.15    44.40
5      2  0.010204        8.00    63.00
6      2  0.210204       59.81    42.38
7      2  0.410204       53.63    42.86
8      2  0.610204       43.75    43.93
9      2  0.810204       38.09    44.75
10     3  0.010204       12.00    63.00
11     3  0.210204       57.86    41.94
12     3  0.410204       53.73    43.28
13     3  0.610204       43.68    43.44
14     3  0.810204       38.44    45.09
15     4  0.010204       16.00    62.00
16     4  0.210204       69.71    42.86
17     4  0.410204       66.67    44.08
18     4  0.610204       59.20    43.75
19     4  0.810204       49.32    44.17